name: Release Status

on:
  push:
    tags:
      - '*'

jobs:   
  tag-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Latest Release ${{ github.ref }}
        body: Draft from commit ${{ github.ref }}
        draft: true
        prerelease: false
      
        
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm release
      run: npm run release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
